#!/bin/bash

set -eu

timedatectl status

fdisk -l ${DISK} # DISK check (e.g.) DISK=/dev/sda
# use gdisk to setup partion
# gdisk ${DISK}1 +1G ef00 # EFI System
# gdisk ${DISK}2 -0G 8304 # Linux root (x86-64)

# make file system
mkfs.fat -F 32 ${DISK}2
mkfs.ext4 ${DISK}1

# mount to /mnt
mkdir -p /mnt/boot
mount ${DISK}2 /mnt
mount ${DISK}1 /mnt/boot

# install essential packages
pacstrap -K /mnt base linux linux-firmware

# generate fstab
genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt
