#!/bin/bash

set -eu

show_help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --username <USERNAME> Specify the username"
    echo "  --wsl                 Skip setup not for wsl"
    echo "  --no-dhcp             Skip dhcpcd setup, NOTE: you need to setup network config manually with this option"
    echo "  --help                Show this help message"
}

# get option --username "username"
USERNAME=""
NODHCP=false
WSL=false
while [[ $# -gt 0 ]]; do
    case "$1" in
    --username)
        [[ -z ${2:-} ]] && (
            echo "Error: Argument required for $1"
            show_help
            exit 1
        )
        USERNAME="$2"
        shift 2
        ;;
    --no-dhcp)
        NODHCP=true
        shift
        ;;
    --wsl)
        WSL=true
        shift
        ;;
    *)
        echo "Unknown option: $1"
        show_help
        exit 1
        ;;
    esac
done

if [[ -z "${USERNAME:-}" ]]; then
    echo "Error: --username is required"
    show_help
    exit 1
fi

echo "set root password"
passwd # root password
# setup user
useradd -m -g users -G wheel -s /bin/bash "$USERNAME"
echo "set ${USERNAME} password"
passwd "$USERNAME"

REGION=Asia
CITY=Tokyo
HOST=arch
hwclock --systohc
ln -sf /usr/share/zoneinfo/${REGION}/${CITY} /etc/localtime

echo -e "en_US.UTF-8 UTF-8\nja_JP.UTF-8 UTF8" >>/etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf

echo "${HOST}" >/etc/hostname

# doas
pacman -S --noconfirm doas
echo "permit persist :wheel" >>/etc/doas.conf
chmod 0600 /etc/doas.conf

# key remap
pacman -S --noconfirm keyd
systemctl enable keyd
echo -e "[ids]\n\n*\n\n[main]\n\ncapslock = overload(control, esc)" >/etc/keyd/default.conf

if $WSL; then
    echo -e "[user]
default=${USERNAME}

[boot]
systemd=true

[network]
hostname=Arch" >/etc/wsl.conf

    su $USERNAME
    mkdir -p "${HOME}/.config/systemd/user"

    cat <<"EOF" >"${HOME}/.config/systemd/user/wsl-wayland-symlink.service"
[Unit]
Description=Create Wayland symlinks for WSL
After=default.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'USER_ID=$(id -u); find /mnt/wslg/runtime-dir -name "wayland-*" -type s -exec ln -sf {} /run/user/$USER_ID/ \;'

[Install]
WantedBy=default.target
EOF
    systemctl --user daemon-reload
    systemctl --user enable wsl-wayland-symlink.service
    systemctl --user start wsl-wayland-symlink.service

else
    # network (dhcpcd and iwd)
    pacman -S --noconfirm dhcpcd iwd
    systemctl enable iwd.service
    if ! $NODHCP; then
        echo "enabling dhcpcd.service"
        systemctl enable "dhcpcd.service"
    else
        echo "you passed --no-dhcp option. skip dhcpcd setup." >&2
        echo "NOTE: you need to setup network config manually with this option." >&2
    fi

    echo "exit from chroot env, reboot and remove install disk"
fi
