#!/bin/bash

set -eu

show_help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --username <USERNAME> Specify the username"
    echo "  --wsl                 Skip setup not for wsl" 
    echo "  --help                Show this help message"
}

# get option --username "username"
USERNAME=""
WSL=false
while [[ $# -gt 0 ]]; do
    case "$1" in
    --username)
        [[ -z ${2:-} ]] && (
            echo "Error: Argument required for $1"
            show_help
            exit 1
        )
        USERNAME="$2"
        shift 2
        ;;
    --wsl)
        WSL=true
        shift
        ;;
    *)
        echo "Unknown option: $1"
        show_help
        exit 1
        ;;
    esac
done

if [[ -z "${USERNAME:-}" ]]; then
    echo "Error: --username is required"
    show_help
    exit 1
fi

echo "set root password"
passwd # root password
# setup user
useradd -m -g users -G wheel -s /bin/bash "$USERNAME"
echo "set ${USERNAME} password"
passwd "$USERNAME"

REGION=ASIA
CITY=Tokyo
HOST=arch
ln -sf /usr/share/zoneinfo/${REGION}/${CITY}
hwclock --systohc

echo -e "en_US.UTF-8 UTF-8\nja_JP.UTF-8 UTF8" >>/etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf

echo "${HOST}" >/etc/hostname

# doas
pacman -S doas
echo "permit persist :wheel" >>/etc/doas.conf
chmod 0600 /etc/doas.conf

if $WSL; then
    echo -e "[user]
default=${USERNAME}

[boot]
systemd=true

[network]
hostname=Arch" >/etc/wsl.conf
else
    # bootloader
    pacman -S grub os-prober efibootmgr
    echo "GRUB_DISABLE_OS_PROBER=false" >>/etc/default/grub
    grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub
    grub-mkconfig -o /boot/grub/grub.cfg

    # dhcp
    pacman -S dhcpcd
    while true; do
      ip l
      interface_count=$(ip l | grep -E "^[0-9]+:" | wc -l)
      echo "Please select a number between 1 and $interface_count:"
      read -r number
    
      if [[ "$number" =~ ^[0-9]+$ ]] && [ "$number" -ge 1 ] && [ "$number" -le "$interface_count" ]; then
    	interface=$(ip l | grep -E "^${number}: " | awk '{print $2}' | sed 's/.$//')
    	echo ${interface}
        systemctl enable "dhcpcd@${interface}.service"
        echo "Enabled dhcpcd@${interface}.service"
        break
      else
        echo "Invalid input. Please select a number between 1 and $interface_count."
      fi
    done

    echo "exit from chroot env, reboot and remove install disk"
fi
