#!/bin/bash

set -eu

show_help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --username <USERNAME> Specify the username"
    echo "  --wsl                 Skip setup not for wsl"
    echo "  --help                Show this help message"
}

# get option --username "username"
USERNAME=""
WSL=false
while [[ $# -gt 0 ]]; do
    case "$1" in
    --username)
        [[ -z ${2:-} ]] && (
            echo "Error: Argument required for $1"
            show_help
            exit 1
        )
        USERNAME="$2"
        shift 2
        ;;
    --wsl)
        WSL=true
        shift
        ;;
    *)
        echo "Unknown option: $1"
        show_help
        exit 1
        ;;
    esac
done

if [[ -z "${USERNAME:-}" ]]; then
    echo "Error: --username is required"
    show_help
    exit 1
fi

echo "set root password"
passwd # root password
# setup user
useradd -m -g users -G wheel -s /bin/bash "$USERNAME"
echo "set ${USERNAME} password"
passwd "$USERNAME"

REGION=Asia
CITY=Tokyo
HOST=arch
hwclock --systohc
ln -sf /usr/share/zoneinfo/${REGION}/${CITY} /etc/localtime

echo -e "en_US.UTF-8 UTF-8\nja_JP.UTF-8 UTF8" >>/etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf

echo "${HOST}" >/etc/hostname

# doas
pacman -S --noconfirm doas
echo "permit persist :wheel" >>/etc/doas.conf
chmod 0600 /etc/doas.conf

# key remap
pacman -S --noconfirm keyd
systemctl enable keyd
echo -e "[ids]\n\n*\n\n[main]\n\ncapslock = overload(control, esc)" > /etc/keyd/default.conf


if $WSL; then
    echo -e "[user]
default=${USERNAME}

[boot]
systemd=true

[network]
hostname=Arch" >/etc/wsl.conf

su $USERNAME
mkdir -p "${HOME}/.config/systemd/user"
cat <<"EOF" > "${HOME}/.config/systemd/user/wsl-wayland-symlink.service"
[Unit]
Description=Create Wayland symlinks for WSL
After=default.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'USER_ID=$(id -u); find /mnt/wslg/runtime-dir -name "wayland-*" -type s -exec ln -sf {} /run/user/$USER_ID/ \;'

[Install]
WantedBy=default.target
EOF
systemctl --user daemon-reload
systemctl --user enable wsl-wayland-symlink.service
systemctl --user start wsl-wayland-symlink.service

else

    # dhcp
    pacman -S --noconfirm dhcpcd
    while true; do
      valid_numbers=()
      declare -A num_to_iface

      mapfile -t interface_lines < <(ip -o l)
      for line in "${interface_lines[@]}"; do
        num=$(echo "$line" | awk -F: '{print $1}')
        iface=$(echo "$line" | awk -F': ' '{print $2}' | awk '{print $1}')
        valid_numbers+=("$num")
        num_to_iface["$num"]="$iface"
      done

      echo "Available intefaces:"
      for num in "${valid_numbers[@]}"; do
        echo "  $num) ${num_to_iface[$num]}"
      done
      echo "  c) Cancel to setup dhcpcd"

      echo "Please select a number from the list above (or 'c' to cancel):"
      read -r number

      if [[ "$number" == "c" ]]; then
        echo "Cancelled to setup dhcpcd by user."
        break
      elif [[ " ${valid_numbers[*]} " =~ " $number " ]]; then
        interface="${num_to_iface[$number]}"
        echo "Selected interface: $interface"
        systemctl enable "dhcpcd@${interface}.service"
        echo "Enabled dhcpcd@${interface}.service"
        break
      else
        echo "Invalid input. Please select one of: ${valid_numbers[*]} c"
      fi
    done

    echo "exit from chroot env, reboot and remove install disk"
fi
