#!/usr/bin/env bash

set -eu

SCRIPT_PATH=$(
    cd $(dirname $0)
    pwd
)
RUN_DEV=true
RUN_DESKTOP=true

CI=${CI:-false} # need to be enabled only CI env

# Function to display help message
show_help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --no-dev      Skip setting up development environment"
    echo "  --no-desktop  Skip setting up desktop environment"
    echo "  --help        Show this help message"
}

# Parse arguments
for arg in "$@"; do
    case $arg in
    --no-dev)
        RUN_DEV=false
        shift
        ;;
    --no-desktop)
        RUN_DESKTOP=false
        shift
        ;;
    --help)
        show_help
        exit 0
        ;;
    *)
        echo "Unknown option: $arg"
        show_help
        exit 1
        ;;
    esac
done

common() {
    doas pacman -S --noconfirm git less man-db neovim nodejs npm poppler tree unzip which yazi
    # dotfiles
    dest_dotfiles="$HOME/.config/dotfiles"
    [ ! -d "$dest_dotfiles" ] && git clone https://github.com/kohei-noda-qcrg/dotfiles "$dest_dotfiles"
    if "${CI}"; then
        PRESETUP_OPTION="--yes"
    fi
    GIT_USERNAME=${GIT_USERNAME:-} GIT_EMAIL=${GIT_EMAIL:-} "$dest_dotfiles/pre-setup" $PRESETUP_OPTION
    "$dest_dotfiles/setup"
    . "$HOME/.bashrc"

    # setup yay
    doas pacman -S --noconfirm git go debugedit fakeroot make clang
    ## update /etc/makepkg.conf
    doas cp /etc/makepkg.conf /etc/makepkg.conf.bak
    grep -q '^PACMAN_AUTH=' /etc/makepkg.conf && doas sed -i 's|^PACMAN_AUTH=.*|PACMAN_AUTH=(doas)|' /etc/makepkg.conf ||
        echo 'PACMAN_AUTH=(doas)' | doas tee -a /etc/makepkg.conf
    ## clone yay
    [ ! -d /tmp/yay ] && git clone https://aur.archlinux.org/yay.git /tmp/yay
    pushd /tmp/yay
    ## build and install yay
    makepkg -si --noconfirm
    popd

    # fzf
    FZFDIR="$HOME/.local/share/fzf"
    if [ ! -d "$FZFDIR" ]; then
        git clone https://github.com/junegunn/fzf $FZFDIR
        $FZFDIR/install --key-bindings --completion --no-update-rc --xdg
    fi
}

setup_dev_environment() {
    doas pacman -S --noconfirm cmake diffutils patch
    doas pacman -S --noconfirm lldb gdb                                     # debugger
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y # rust
    . $HOME/.cargo/env

    # uv Python package manager
    curl -LsSf https://astral.sh/uv/install.sh | sh
    doas pacman -S --noconfirm python python-pip

    doas pacman -S --noconfirm github-cli glab pkgconf zellij
}

setup_desktop_environment() {
    doas pacman -S --noconfirm noto-fonts-cjk fcitx5-im fcitx5-mozc
    cat "${SCRIPT_PATH}/files/etc/environment" | doas tee -a /etc/environment

    doas pacman -S --noconfirm alacritty brightnessctl hyprland hypridle hyprlock hyprshot ttf-font-awesome waybar wofi xorg-xwayland qt5-wayland wl-clipboard

    mkdir -p ~/.config/sway

    doas pacman -S --noconfirm pipewire pipewire-pulse
    if ! "${CI}"; then
        systemctl --user --now enable pipewire{,-pulse}.{socket,service}
        systemctl --user start pipewire{,-pulse}.service
    fi

    doas pacman -S --noconfirm firefox
    doas pacman -S --noconfirm xdg-desktop-portal-hyprland # for screen share
}

common
$RUN_DEV && setup_dev_environment
$RUN_DESKTOP && setup_desktop_environment
