#!/usr/bin/env bash

set -eu

RUN_DEV=true
RUN_DESKTOP=true

# Function to display help message
show_help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --no-dev      Skip setting up development environment"
    echo "  --no-desktop  Skip setting up desktop environment"
    echo "  --help        Show this help message"
}

# Parse arguments
for arg in "$@"; do
    case $arg in
    --no-dev)
        RUN_DEV=false
        shift
        ;;
    --no-desktop)
        RUN_DESKTOP=false
        shift
        ;;
    --help)
        show_help
        exit 0
        ;;
    *)
        echo "Unknown option: $arg"
        show_help
        exit 1
        ;;
    esac
done

common() {
    # setup yay
    doas pacman -S git go debugedit fakeroot make clang
    pushd /tmp
    if [[ ! -d yay ]]; then
        git clone https://aur.archlinux.org/yay.git
    fi
    cd yay
    makepkg -si
    yay -Syu
    popd

    doas pacman -S neovim nodejs npm
}

setup_dev_environment() {
    doas pacman -S lldb # debugger
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh # rust
    . $HOME/.cargo/env

    # uv Python package manager
    curl -LsSf https://astral.sh/uv/install.sh | sh
    . $HOME/.local/bin/env
    python3_ver="3.13.1"
	uv tool update-shell
	uv python install --default --preview "$python3_ver"

    yay -Sy
    yay -S github-cli

    gh auth login
}

setup_desktop_environment() {
    doas pacman -S noto-fonts-cjk fcitx5-im fcitx5-mozc

    doas pacman -S alacritty sway xorg-xwayland qt5-wayland wl-clipboard
    mkdir -p ~/.config/sway
    sed 's/set \$term foot/set \$term alacritty/' /etc/sway/config >~/.config/sway/config

    doas pacman -S pipewire pipewire-pulse
    systemctl --user --now enable pipewire{,-pulse}.{socket,service}
    systemctl --user start pipewire{,-pulse}.service

    doas pacman -S firefox
}

common
$RUN_DEV && setup_dev_environment
$RUN_DESKTOP && setup_desktop_environment
