#!/usr/bin/env bash

set -eu

# sadly, hyprland requires NVIDIA proprietary drivers
# when using NVIDIA GPUs, so we need to install them

doas pacman -S --noconfirm nvidia-dkms nvidia-utils linux-headers

file="/etc/modprobe.d/nvidia.conf"
doas mkdir -p "$(dirname "$file")"
echo "options nvidia-drm modeset=1" | doas tee "$file" >/dev/null

file="/etc/mkinitcpio.conf.d/nvidia.conf"
doas mkdir -p "$(dirname "$file")"
echo "MODULES+=(nvidia nvidia_modeset nvidia_drm nvidia_uvm)" | doas tee "$file" >/dev/null

doas mkinitcpio -P
doas dkms autoinstall

echo "NVIDIA proprietary drivers installed successfully."
echo "Note: you need to add 'nvidia-drm.modeset=1' to your kernel parameters."
echo "Please reboot your system to apply the changes."
