name: test-02-setup-dev-and-desktop-env

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: -v ${{ github.workspace }}:/github/workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update system
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm git doas coreutils shadow
          useradd -m -g users -G wheel -s /bin/bash test
          echo "permit nopass test" >>/etc/doas.conf
          chmod 0600 /etc/doas.conf
      - name: run test
        run: su test -c 'CI=true GIT_USERNAME=test GIT_EMAIL=test@test.com /github/workspace/02-setup-dev-and-desktop-env'
